version: '3'
services:
  webserver:
    image: puckel/docker-airflow
    restart: always
    volumes:
      - ./dags:/usr/local/airflow/dags
    ports:
      - "8080:8080"
      - "5432:5432"
    command: webserver
    environment:
          - DB_PASS=${DB_PASS}
          - DB_USER=${DB_USER}
          - DB_URL=${DB_URL}
          - DB_NAME=${DB_NAME}
          - FROST_API_CLIENT_ID=${FROST_API_CLIENT_ID}
